//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Windows.Forms;

namespace ProdigalSoftware.TiVEEditor.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0, 0, 0")]
        public Rectangle MainEditorBounds {
            get {
                return ((Rectangle)(this["MainEditorBounds"]));
            }
            set {
                this["MainEditorBounds"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public FormWindowState MainEditorState {
            get {
                return ((FormWindowState)(this["MainEditorState"]));
            }
            set {
                this["MainEditorState"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string BlockEditorImportLastDir {
            get {
                return ((string)(this["BlockEditorImportLastDir"]));
            }
            set {
                this["BlockEditorImportLastDir"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string BlockEditorBlockListLastDir {
            get {
                return ((string)(this["BlockEditorBlockListLastDir"]));
            }
            set {
                this["BlockEditorBlockListLastDir"] = value;
            }
        }
    }
}
